const byte DETAIL_FINISHED          = 0;  // finished
const byte DETAIL_ALL_BAD           = 1;  // all bad
const byte DETAIL_ERR_READ_FILE     = 2;  // error read file
const byte DETAIL_SET_STATE_BAD     = 3;  // change state bad
const byte DETAIL_SET_STATE_OK      = 4;  // change state ok
const byte DETAIL_BAD_VALUE         = 5;  // bad value
const byte DETAIL_ERR_WRITE_FILE    = 6;  // error write file
const byte DETAIL_CORRECT_UPDATED   = 7;  // correct updated
const byte DETAIL_FILE_REMOVED      = 8;  // file removed
const byte DETAIL_WATERING_UPDATED  = 9;  // watering updated
const byte DETAIL_ENABLED           = 10; // enabled
const byte DETAIL_DISABLED          = 11; // disabled
const byte DETAIL_STOPPED           = 12; // stopped
const byte DETAIL_NOW_LESS_CORRECT  = 13; // now < last correct
const byte DETAIL_ACCURACY_OVERRIDE = 14; // override
const byte DETAIL_MEASURE_COMPLETED = 15; // measure completed
const byte DETAIL_MEASURE_WRITED    = 16; // measures writed
const byte DETAIL_STOP              = 17; // stop
